version: "1.0"
services: #only for dev
  app:
    build: .
    ports:
      - "8080:8080"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  test_mongo:
    image: mongo
    ports:
      - "27017:27017"